let suggestions = [
  "Coding Maker",
  "Coding Maker programing",
  "Coding Maker Java programing",
  "Coding Maker C# programing",
  "Coding Maker C programing",
  "Coding Maker C++ programing",
  "Coding Maker PHP programing",
  "Coding Maker paython programing",
  "Coding Maker  data",
  "How to learn HTML",
  "How to learn HTML and CSS",
  "How to learn HTML and CSS and SASS",
  "How to learn HTML and CSS and SASS and BootStrap",
  "How to learn JavaScript",
  "How to learn JavaScript Dome",
  "How to learn JavaScript Golb",
  "How to learn JavaScript and Jquery",
  "How to learn Java programing",
  "How to learn C porgraming",
  "How to learn C++ porgraming",
  "How to learn C# porgraming",
  "How to learn PHP porgraming",
  "How to learn paython porgraming",
  "How to learn Database",
  "How to learn Database mysql",
];
